austin.intro.1.jamie.coe
AustinCodingAcademy/web-workbook pull request #113
Opened 2016-10-11 01:53 UTC by poocallah

2016-10-23 01:55 UTC, ivome requested changes
Great work! I just commented on some minor formatting things. It will pay off to write clean HTML with a good style.

2016-10-23 01:55 UTC, ivome commented on 02Lesson/01Homework/index.html
> +</table>
The indentation is missing here or inconsistent. Did the change in Atom from Tab to spaces mess that up? Try to make this consistent for all elements.

2016-10-23 01:55 UTC, ivome commented on 02Lesson/01Project/index.html
> +      <ol type="1">
´ol´ tag should start on the same level as ´h3´ tag.

2016-10-23 01:55 UTC, ivome commented on 02Lesson/01Project/index.html
> +    <h3>What we offer</h3>
I would always recommend to close all block elements on the same level they are opened:
```html
<h3>
   What we offer
</h3>
´´´

2016-10-23 01:55 UTC, ivome commented on 02Lesson/02Homework/index.html
> +        </aside>
`aside` closed on different indentation level than opened.

2016-10-23 01:55 UTC, ivome commented on 02Lesson/02Homework/index.html
> +    <footer>
Next opening element (in this case `footer`) after closing `aside` should be on the same indentation level.

2016-10-23 01:55 UTC, ivome commented on 02Lesson/02Project/index.html
> +      <h2>
Usually you would use `h2` tags only for real headlines, not to build a navigation bar. But since we were experimenting, this is fine here...

2016-10-23 01:55 UTC, ivome commented on 02Lesson/02Project/index.html
> +        <p>WikiLinks' founder, Julian Assange's internet access has been cut by an unknown state actor.
For better readability put block elements on its own line: 
```
<p>
   My text here....
</p>
````

2016-10-23 01:55 UTC, ivome commented on 02Lesson/02Project/index.html
> +      <p>© 2016 Daily Planet
Same here...

2016-10-23 01:55 UTC, ivome commented on 03Lesson/01Project/css/style.css
> +.headertext{
Add space before opening bracket for better readability.

2016-10-23 01:55 UTC, ivome commented on 03Lesson/01Project/css/style.css
> +  padding-top:20px;
Add space before value

2016-10-23 01:55 UTC, ivome commented on 03Lesson/01Project/css/style.css
> +  color:#eeffff
Missing semicolon

2016-10-24 00:36 UTC, poocallah commented on 02Lesson/01Homework/index.html
> +</table>
It did mess it up a bit. I'll go back through and try to make the proper spaces

2016-10-26 16:01 UTC, poocallah commented on 02Lesson/01Homework/index.html
> +</table>
I deleted all the code and rewrote everything, but it still came up that tabs were used. To make it "happy", I pushed everything to the far left. The code for this looks terrible, but I'd rather not see this fail every time I commit something. Will look into this issue further.

2016-11-03 00:39 UTC, zacacollier commented on 03Lesson/01Homework/css/style.css
> +}
You'll need to add one more css property to this selector to get the text vertically centered properly - what do you think that could be?

2016-11-04 20:29 UTC, poocallah commented on 03Lesson/01Homework/css/style.css
> +}
Would that be, margin: auto; ? I've tried that and also, vertical-align: middle;  with it not changing. Think I'll try rewriting this using flexbox, this weekend.

2016-12-19 22:27 UTC, ivome commented on 11Lesson/01Homework/css/style.css
> +  display: flex;
Don't mix flexbox with the bootstrap grid system. If you want to use flexbox, create another container and place it **inside** of the column element that has the `col-*-*` class

2016-12-19 22:27 UTC, ivome commented on 11Lesson/01Homework/css/style.css
> +  background: linear-gradient( rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3) ), url("../img/wine13.jpg");
If you have two times the same color, you don't need a gradient. Background-color works just fine.

2017-01-05 17:17 UTC, closed without merging