austin.intro.1.andrew.flater
AustinCodingAcademy/web-workbook pull request #121
Opened 2016-10-11 01:53 UTC by aflater

2016-10-23 13:27 UTC, ivome requested changes
You have a few issues in your code that are really easy to fix:
I would go through your code again and first try to fix the indentation. It might be easier to just create the documents from scratch and check often. Maybe have someone in a learning group look over your code while you do this. 
Then save often and check for the W3C validation errors in Atom. Once you have done that, all the errors in your code should be fixed... ;-) 
Without indentation you will keep making a lot of unnecessary mistakes. 
Keep it up!!

2016-10-23 13:27 UTC, ivome commented on 01Lesson/index1
> +Your first website
Most files should have a file extension like `.html` or `.md`

2016-10-23 13:27 UTC, ivome commented on 02Lesson/01Homework/index.html
> +  <body style="background-color: aqua"> </p>
No body element allowed in `head` section. Closing `p` tag before opening tag.

2016-10-23 13:27 UTC, ivome commented on 02Lesson/01Homework/index.html
> +<h1>ANDREW ROBERT FLATER</h1>
Indentation: All child elements of body element need to be indented by 2 spaces.

2016-10-23 13:27 UTC, ivome commented on 02Lesson/01Homework/index.html
> +  Going to school to be a Computer Programmer.
Missing closing `p` tag.

2016-10-23 13:27 UTC, ivome commented on 02Lesson/01Homework/index.html
> +      <li>Favorite Sports</li>
Missing closing `ol` tag.

2016-10-23 13:27 UTC, ivome commented on 02Lesson/01Homework/index.html
> +<h2>My favorite Websites</h2>
Indentation...

2016-10-23 13:27 UTC, ivome commented on 02Lesson/01Homework/index.html
> +  <a href="https://www.chelseafc.com">Chelsea FC<img src="http://www.chelseafc.com/content/cfc/en/ref/clubs/en/chelsea.img.png"/>
Missing closing `a` tag.

2016-10-23 13:27 UTC, ivome commented on 02Lesson/01Project/index.html
> +<a href="https:///www.skylinepetcareaustin.com/"> CLICK HERE FOR CLIENT REVIEWS</a>
Check the indentation for the page

2016-10-23 13:27 UTC, ivome commented on 02Lesson/02Project/index.html
> +        </h1>
Element `nav` not allowed as child element `h1`. Indentation of closing `h1` tag is wrong.

2016-10-23 13:27 UTC, ivome commented on 02Lesson/02Project/index.html
> +          <a href="https://www.nbcnews.com">Election Day 2016</a>
Too many spaces as indentation.

2016-10-23 13:27 UTC, ivome commented on 02Lesson/02Project/index.html
> +    <aside>
Indentation.

2016-10-23 13:30 UTC, ivome commented
How you can check your result: See if the tests in your pull request are passing. You should have a green checkmark next to your pull request. Click on the details for circleci if you see any errors, that will tell you where to look in your code.

2016-10-25 18:25 UTC, aflater commented
Thank you Ivo. I'm meeting with the group today to go over stuff. See you
monday!

On Sun, Oct 23, 2016 at 8:30 AM, Ivo Meißner <notifications@github.com>
wrote:

> How you can check your result: See if the tests in your pull request are
> passing. You should have a green checkmark next to your pull request. Click
> on the details for circleci if you see any errors, that will tell you where
> to look in your code.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/AustinCodingAcademy/web-workbook/pull/121#issuecomment-255588681>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVtCNF2cTHCbXuLqxW6gIKwvkqiintIuks5q22F7gaJpZM4KTKWu>
> .
>

2017-01-02 20:37 UTC, aflater commented
Hey Ivo, 
it's Andrew flater just want to see when you think the grades will be up?

Andrew 

Sent from my iPhone

> On Oct 23, 2016, at 8:30 AM, Ivo Meißner <notifications@github.com> wrote:
> 
> How you can check your result: See if the tests in your pull request are passing. You should have a green checkmark next to your pull request. Click on the details for circleci if you see any errors, that will tell you where to look in your code.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-01-04 10:29 UTC, ivome commented
Great Job catching up!! 
You build a really nice looking final project. Unfortunately there is a few things missing like a map and forms and one of those optional javascript modules, or did I miss something? Also, did you mean to place the content boxes at the bottom next to each other? 
The task for lesson 12 project was to replicate the given layout. I would recommend to build that, since it requires some interesting applications of the grid system.

2017-01-04 13:25 UTC, aflater commented
Hi Ivo,

 thank you so much for the feedback. For practice I'm just gonna start over and try to redo everything also bought several books to get me ready for next semester. I've already started looking at it. Thanks again for a great semester! 
Hi 
Andrew

Sent from my iPhone

> On Jan 4, 2017, at 4:29 AM, Ivo Meißner <notifications@github.com> wrote:
> 
> Great Job catching up!!
> You build a really nice looking final project. Unfortunately there is a few things missing like a map and forms and one of those optional javascript modules, or did I miss something? Also, did you mean to place the content boxes at the bottom next to each other?
> The task for lesson 12 project was to replicate the given layout. I would recommend to build that, since it requires some interesting applications of the grid system.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-01-05 17:17 UTC, closed without merging